splitrb/split

.travis.yml
Gemfile
lib/split/alternative.rb
lib/split/dashboard.rb
lib/split/experiment.rb
lib/split/experiment_catalog.rb
lib/split/helper.rb
lib/split/metric.rb
lib/split/persistence/redis_adapter.rb
lib/split/trial.rb
spec/algorithms/weighted_sample_spec.rb
spec/algorithms/whiplash_spec.rb
spec/alternative_spec.rb
spec/dashboard_spec.rb
spec/encapsulated_helper_spec.rb
spec/experiment_catalog_spec.rb
spec/experiment_spec.rb
spec/helper_spec.rb
spec/metric_spec.rb
spec/persistence/redis_adapter_spec.rb
spec/spec_helper.rb
spec/trial_spec.rb
split.gemspec

This closes #285 
A decent amount of refactoring done here, but it should clean things up quite a bit. No changes were made to the helper API and all of the specs are passing.

Decouple trial from Split::Helper

---

README.md

Hi,
the snippet not works anymore with Rails 4.1. I've updated with the new syntax, works even with Rails 2.10. See [env](http://apidock.com/rails/Rails/env/class) and [root](http://apidock.com/rails/Rails/root/class) doc for more info.

Update initializer code with Rails.root and Rails.env

---

lib/split/configuration.rb
lib/split/experiment.rb
lib/split/trial.rb
spec/configuration_spec.rb
spec/experiment_spec.rb
spec/trial_spec.rb

This allows metadata to be associated with an experiment. Very useful when you need more than an alternative name to change behaviour. The current way to solve this problem is to have a conditional statement around the experiment code to decide on the conditional branch. With this change, it is possible to choose what is in the trial metadata.
```ruby
if (trial.alternative.name == "a")
else (trial.alternative.name == "b")
end
```
```yaml
my_first_experiment:
alternatives:
- a
- b
meta:
a:
text: "Have a fantastic day"
b:
text: "Don't get hit by a bus"
```
``` ruby
> trial.alternative.name
> trial.metadata['text']
```
Fixes #288

Added metadata to experiment.

---

lib/split/dashboard/public/style.css

In the dashboad, to prevent experiments with long names from overflowing:
Remove the `max-width: 800px` style from the body:

Remove body "max-width" from dashboard.

---

CHANGELOG.md
README.md

Am I correct in believing that this is a breaking change? If so, was it intentional?

Update documentation regarding Split::Experiment.

---

lib/split/helper.rb

Protip: Don't delete a redis instance your production server is currently using.
If wanted, I can add both:
1. Checking for the specific error message DNS resolution failures produce: `getaddrinfo: Name or service not known`
2. A test for raising this specific error, though I'm not exactly where it should go. The `helper_spec.rb` file does have tests for redis being unavailable, but it currently only tests the raise of `Errno::ECONNREFUSED` and not `Redis::CannotConnectError`.

If the DNS resolution fails for your redis server, ruby will throw a SocketError, which is currently not rescued by the ab_test helper

---

lib/split/helper.rb

Since this code was previously merged, Rails has changed and currently
(at 4.2) this code has not been working in controllers, because the
condition was true also for capture method from Kernel::Reporting module
from Rails.

Don't check for capture presence in ab_test

---

README.md

This fixes the example to properly setup a test where the "New" alternative is shown 10% of the times. I realize the example is less sexy, but this is how the `WeightedSample` algorithm works.

Change Weighted alternatives example

---

README.md

- if you are on ruby 1.8 chances are you are not adding new fancy gems
- same goes for rails 2.3
- rails does not need the require
- if you use bundler you most likely know howto add gems to it
- make bash commands copy pasteable by removing the $
@andrew a few random fixes, let me know which ones you like :)
[Preview](https://github.com/grosser/split/blob/a44547e872ab4c1a866a7492641b00165280b28c/README.md)

simplify installation instructions

---

README.md

@andrew 
- switch to 1.9 syntax
- use symbols for every name
(I'm atm using split with all symbols and works just fine ...)
[Preview](https://github.com/grosser/split/blob/grosser/symbols/README.md)

modernize and symbols

---

README.md

This is necessary in order to allow Delete Experiment from the Admin panel

Update Warden Authentication Example to include :delete.

---

README.md
lib/split.rb
lib/split/configuration.rb
spec/configuration_spec.rb

Noticed that there was only a footnote on how to change the Redis url below configuration. I wrote the following changes and added in tests for the default behavior as well.
It wasn't until I was reviewing the `README.md` in preview mode to make sure the changes looked correct that I noticed the [Redis](https://github.com/splitrb/split#redis-1) section that talks about overwriting `Split.redis` directly.

allow for custom redis_url different from ENV variable

---

README.md

Quite a minor gripe, but the example on the README doesn't work (bad indentation + the key is incorrect).

Fixes experiment metadata doc

---

README.md
lib/split/configuration.rb
lib/split/persistence/cookie_adapter.rb
spec/configuration_spec.rb

This adds the ability to change the length of the persistence cookie to a time period other than 1 year.

Cookie length config

---

lib/split/experiment.rb

Extract common code from Experiment#save in Expriment#save_goals,
Experiment#save_metadata methods in order to remove duplication.

Remove duplication from Experiment#save

---

lib/split/experiment.rb

The method accepts argument "alternative_probabilities" but uses
instance variable "@alternative_probabilities" instead turning the
argument unnecessary.
Closes #311

Remove unnecessary argument of Experiment#write_to_alternatives

---

lib/split/helper.rb
spec/helper_spec.rb

Fix to this issue: https://github.com/splitrb/split/issues/330

fix active experiments when experiment is on a later version

---

lib/split/dashboard/views/_experiment.erb
lib/split/experiment.rb
spec/experiment_spec.rb

It looks like when this feature was added the calculation of winning alternatives was meant to take place only once per day.
The `#calc_winning_alternatives` method was never called, which was meant to be saving the experiment's last `calc_time`.
Update the experiment view to call this method instead of the `#estimate_winning_alternative` method directly. Fix caching so that the `#calc_time=` metreturn value of hod is called, rather than assigning to a local variable. Update `calc_time` so that number of days since epoch is stored, rather than the day of month (1-31). Ensure we're comparing integer values, rather than the string value Redis returns from `#hget`.
It's worth noting that this pull request changes the value that `#calc_winning_alternatives` returns - it will now return `nil` …

Fix caching of winning alternative

---

lib/split/helper.rb

Redis defines a number of different exception classes (see https://github.com/redis/redis-rb/blob/1bd43346cdf71ba69176612714616289a5a70ed4/lib/redis/errors.rb for details). When Redis raises an exception, we need to be able to have the db_failover configuration used, whether it's a failure to connect, a timeout, or an invalid command.
We ran into this issue when our Redis instance ran out of memory. In that case (and most others), Split should be able to handle things gracefully.

Rescue from Redis::BaseError in #ab_test

---

README.md
lib/split/dashboard.rb
lib/split/dashboard/views/_controls.erb
lib/split/dashboard/views/_experiment.erb
lib/split/experiment.rb
spec/dashboard_spec.rb

I've got a fairly complex split install. Some experiments have names like url path segments and and ‘/‘ messes up the dashboard JS and sinatra routing when one of those names is used as a pretty url parameter, even though it's a valid experiment name for the rest of split.
This makes minor changes to the routing for the `post` and `delete` routing and updates the HTML to pass the experiment name as a query string.

Fix the dashboard for experiments with ‘/‘ in the name.

---

lib/split/dashboard/public/dashboard-filtering.js
lib/split/dashboard/public/style.css
lib/split/dashboard/views/_experiment.erb
lib/split/dashboard/views/index.erb
lib/split/dashboard/views/layout.erb

This pull requests aims to address part of https://github.com/splitrb/split/issues/340#issuecomment-194986886. It adds very simplistic filtering to the split dashboard, allowing the user to narrow results by experiment name.

Implement naive dashboard filtering by experiment name

---

lib/split/dashboard/public/dashboard-filtering.js
lib/split/dashboard/views/_experiment.erb
lib/split/dashboard/views/index.erb

This is a follow-up to #363. It adds the ability to toggle between active/completed experiments at the top, with the "Clear filters" button resetting the page state. It's a really simple implementation but provides some helpful functionality.
Let me know if you'd like to see any changes.

Implement filtering dashboard by active/complete experiments

---

README.md
lib/split/experiment.rb
spec/experiment_spec.rb

When Split is configured to start experiments manually, deleted experiments will be re-initialized and immediately active unless there is a re-deployment with `ab_test` code for that experiment removed.  This change ensures that Split respects the `start_manually` configuration for this case without requiring code cleanup and re-deployment.

respect manual start configuration  after an experiment has been deleted

---

README.md
lib/split.rb
lib/split/encapsulated_helper.rb
lib/split/helper.rb
lib/split/trial.rb
lib/split/user.rb
spec/encapsulated_helper_spec.rb
spec/helper_spec.rb
spec/spec_helper.rb
spec/trial_spec.rb
spec/user_spec.rb

When `config.allow_multiple_experiments = true`, if the user has previous been in any experiment, that is gone, stopped, or a winner has been chosen, he/she will not be placed in a new experiment. The proposed solution creates a new abstraction class User and cleans up old experiments that are no longer active (i.e. gone, stopped or a winner has been chosen)
Addresses: https://github.com/splitrb/split/issues/337#issuecomment-204088887

Clean up experiments that are gone, stopped or a winner has been chosen

---

lib/split/configuration.rb

**What was missing**
* While reading the configurations for experiments, `algorithm` key was ignored. In-fact other configuration_keys like `resettable`, `goals`, `alternatives` were being considered.
**What is implemented in this PR**
* While reading all configurations at `../lib/configuration.rb` (forex: by function `Split.configuration.experiment_for(@name)` ), `algorithm` key was taken into account along with other config_keys
**Related Issue**
https://github.com/splitrb/split/issues/344

Allow algorithm configuration at experiment level

---

lib/split/trial.rb
spec/trial_spec.rb

Storing the override wouldn't increment participant count but would 'finish' an experiment

increment participation if store override is true and no experiment key exists

---

lib/split/helper.rb
lib/split/trial.rb
lib/split/user.rb
spec/user_spec.rb

Growing the User abstraction; refactoring

---

README.md
lib/split/encapsulated_helper.rb
lib/split/helper.rb
spec/helper_spec.rb

Addressing https://github.com/splitrb/split/issues/298

Renaming finished() method to less generic ab_finished()

---

lib/split/experiment.rb

Experiment#save_metadata is called in the previous line, which
resulted in calling `Split.redis.set(metadata_key, @metadata.to_json)`
twice. I removed the unecessary line.

Remove unecessary code from Experiment#save

---

lib/split/experiment.rb

Experiment#set_alternatives_and_options appeared both in the `if`
section and in the `else` section. I moved `set_alternatives_and_options`
out of the `if...else` block so that it is more DRY.
I am not sure if setting only options[:alternatives] in the `else`
clause is more readable than explicitly providing a hash with the attributes
to set as it happens in the `if` clause.

DRY Experiment#initialize

---

lib/split/trial.rb

PR for Issue #406 Extraneous request to RedisAdapter

Eliminate extra RedisAdapter hget

---

lib/split/experiment.rb
lib/split/user.rb
spec/user_spec.rb

This fixes a major bug when negative non-finished numbers appear and simple random exception fired on the dashboard. Actually, without this fix all experiments which are finished with "reset: false" produce invalid results.
The problem was with User#cleanup_old_experiments! method because it treats “experimen1:finished” key as a non-found experiment and just deletes it.
Related issues:
https://github.com/splitrb/split/issues/43
https://github.com/splitrb/split/issues/103
https://github.com/splitrb/split/issues/133
https://github.com/splitrb/split/issues/355
https://github.com/splitrb/split/issues/294
https://github.com/splitrb/split/issues/272

FIX Negative numbers on non-finished

---

README.md
lib/split/persistence/redis_adapter.rb

Issue #403 Support TTL for participants in RedisAdapter

Add `expire_seconds:` TTL option to RedisAdapter

---

lib/split/user.rb
spec/user_spec.rb

Update `Split::User` to accept an optional persistence adapter, overriding the default.
This allows for running experiments outside a web request that are tied to a particular "user". By making use of `Split::User` when running the experiment, you're able to initiate the experiment one day and record a completion at a later time (by retrieving the earlier trial).
**Running an experiment**
```ruby
experiment_name = :welcome_message
key = "thing-#{thing.id}"
ab_user = Split::User.new(Split::Persistence.adapter.new(nil, key)
experiment = Split::ExperimentCatalog.find_or_create(experiment_name)
trial = Split::Trial.new(user: ab_user, experiment: experiment)
trial.choose!
if trial.alternative.name == "short_message"
send_short_message
elsif trial.alternative.name == "long_message" …
```

Optional custom persistence adapter

---

README.md
lib/split/user.rb
spec/helper_spec.rb

use config.allow_multiple_experiments = 'control' for multiple experiments per user with at most 1-non-control

Issue #405 Running concurrent experiments on same endpoint/view

---

README.md
lib/split/helper.rb
spec/helper_spec.rb

As discussed in #381.
Verified that both Rails and Sinatra parse [] in params to nested hashes this way.
Per #396, maybe "split_test" would be a better namespace?

Namespaced override param

---

lib/split/configuration.rb

Heroku Redis services often use the REDIS_PROVIDER variable to set the name of the variable which contains the Redis URL I'm using `config.redis_url` option but I think we should add support for REDIS_PROVIDER so Split works with minimal configuration.
As you can see Sidekiq also supports it: 
https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/redis_connection.rb#L93
```
def determine_redis_provider
ENV[ENV['REDIS_PROVIDER'] || 'REDIS_URL']
end
```
In this pull request I've followed that method but used ENV.fetch as that was what was used before.

Support REDIS_PROVIDER variable used in Heroku

---

README.md
lib/split.rb
lib/split/configuration.rb
spec/configuration_spec.rb
spec/split_spec.rb
split.gemspec

I was just wondering how open everyone would be to a future version removing the dependency on `redis-namespace`.
It seems like the [`Split.redis=`][method] is basically just doing some magic that accepts either:
* A url (either from `ENV['REDIS_URL']` or one supplied during configuration),
* a `Redis` instance, which is then namespaced automatically, or
* a `Redis::Namespace` instance.
Right now, the URL doesn't necessarily need to adhere to the [spec][redis-url]. I would be happy to work on a solution that simplifies the assignment to allow either:
1. A string as a [fully-qualified redis URL][redis-url]. This would still default to `ENV['REDIS_URL']` and would be passed as `{url: self.configuration.redis_url}` to `Redis.new`.
2. A hash passed directly to `Redis.new`.
3. Otherwise assume …

Remove dependency on Redis::Namespace

---

lib/split.rb
lib/split/configuration.rb
lib/split/experiment.rb
lib/split/goals_collection.rb
lib/split/redis_interface.rb
spec/experiment_spec.rb
spec/redis_interface_spec.rb

We would prefer never to reset the data even if the variants change names, the metadata changes, etc. I've added a `reset_manually` configuration flag that makes this possible, and refactored the Redis persistence so that it applies incremental changes rather than blowing away all experiment data before it's rewritten.

Make resetting on experiment change optional

---

lib/split/alternative.rb

Hey everybody, first PR for this repo, so let me know if I have overlooked something. I noticed when reading through the alternative.rb file, there is an explicit 'return' of the winner. Is there a reason you choose to do this? This code will always return the last evaluated line. Also, this is set to be an instance variable, but is not used anywhere. Thoughts?
The style guide(https://github.com/bbatsov/ruby-style-guide#no-explicit-return) says:

Remove Explicit Return

---

README.md

I should have caught these in my PR (#425) but didn't.
This PR:
* Updates the **Namespaces** documentation to reflect `redis-namespace` no longer being a dep.
* Adds documentation about `REDIS_PROVIDER` support.

Update Redis config docs

---

README.md

needs to be updated after
https://github.com/splitrb/split/commit/327e02221e206b2f5f3efe9c635a9f6cbbd8db3c
Otherwise, fails with invalid uri error

Add redis:// scheme name to README

---

lib/split/dashboard.rb
lib/split/dashboard/views/_experiment.erb
spec/dashboard_spec.rb

From #427 -- This simply allows selecting the current users variation/alternative on the dashboard. Helpful for when you're debugging a single alternative and don't want to keep overriding the URL parameter.
Example:
Note: Not happy with the copy, but it's late and I couldn't think of anything else. :)

Add ability to force alternative on dashboard

---

lib/split/extensions.rb
lib/split/extensions/array.rb
spec/spec_helper.rb

1.8 hasn't been supported by Split in a long time, these couple of hacks must have slipped through the net

Removed a couple old ruby 1.8 hacks

---

lib/split/dashboard/public/dashboard-filtering.js
lib/split/experiment.rb

Fixed a few codeclimate warnings

---

lib/split/alternative.rb
lib/split/dashboard/views/_experiment.erb
lib/split/helper.rb
spec/alternative_spec.rb

Note that the current master branch on `splitrb/split` has 1 failed test

Add ab_record_extra_info to allow record extra info to alternative and display on dashboard.

---

README.md

Use public secure_compare with digests to do the same work as private method variable_size_secure_compare.

Avoid variable_size_secure_compare private method

---

lib/split/configuration.rb

I've discovered a few more common bots that are probably worth adding to the default block list:
* YandexAccessibilityBot http://yandex.com/bots
* YandexMobileBot http://yandex.com/bots
* LinkedInBot http://www.linkedin.com
* Pinterest http://www.pinterest.com/bot.html
* Slackbot https://api.slack.com/robots

Blocked a few more common bot user agents

---

lib/split/helper.rb

Use case: At the start of each of our Rail app's request, we grab the current user's set of experiments to be included in application logs. We had been using `ab_user.active_experiments` to grab this information, but we discovered that this function did not honor the `db_failover` option (ie - it resulted in our application crashing due to the unhandled exception). This PR adds a new convenience function which returns a user's set of experiments while also honoring the `db_failover` configuration setting.

Enumeration of a User's Experiments that Respects the db_failover Option

---

lib/split/persistence/cookie_adapter.rb
spec/persistence/cookie_adapter_spec.rb

CookieAdapter receives the 'context' passed down to the User instance. Which is different on a Sinatra(Dashboard) and a Rails App.
As they are both Rack instances, the easier way to keep it working for both Rails and Sinatra I used the request/response to read/write the cookies from Rack directly.
Also updated the Specs to test against mock Rack requests.  @andrew Please let me know what you think!
Fixes #480

Rewrite CookieAdapter  to work with Rack::Request and Rack::Response directly

---

.travis.yml
README.md
spec/experiment_spec.rb
spec/persistence/dual_adapter_spec.rb
split.gemspec

Following on from #498, closes #494 
As long as the installed version of rubygems is 2.0.0 or greater, everything still works on 1.9.3 so let's keep it that way for better backwards compatibility.

Add 1.9.3 support back in

---

.rubocop.yml
README.md
lib/split/configuration.rb
lib/split/experiment.rb

If you're running A/B tests for a short period of time, the "Probability of being Winner" numbers can be unhelpful or misleading.

Allow configuration of how often winning alternatives are recalculated

---

lib/split/alternative.rb
spec/alternative_spec.rb

At normal operation, it's not possible for an experiment alternative
to have a `participant_count` > `completed_count`.
However, by manually using `increment_participation`
(for a custom use-case or by accident) you can arrive
on such a situation.
If that happens, `Zscore.calculate` produces an error that
propagates all the way up to the web view.
Solution:
In the cornercase of a conversion rates taking a value >1,
it makes no sense to calculate a zscore value at all.
An escape clause was added

Avoid z_score numeric exception for conversion rates >1

---

lib/split/combined_experiments_helper.rb
spec/combined_experiments_helper_spec.rb

1. always pass all alternatives to prevent unintentional version bumps
2. return the chosen alternative from `ab_combined_test`
Fixes #500

Fix combined experiments

---

README.md

Updated README.md Rails 3 -> Rails 3 or higher ❤️ 
this change would be more helpful for new users

split dashboard works with rails 3 or higher

---

lib/split/redis_interface.rb

See Redis `LTRIM` command docs [here](https://redis.io/commands/ltrim).
Commit description:
> This implementation will only execute 1 to Redis command, instead of
> 2n (n being the total number of elements to trim from the list).
> 
> The operation will still take O(n) time, but the constants will be
> much better, since only 1 network round trip is required.
A small improvement, but I happened to notice while looking around the code. Admittedly, it doesn't seem this method is currently used with a lot of data, but I think it's easy to imagine it having a significant impact on performance if used differently in the future.
I'd be happy to submit a benchmark if that would be helpful :).

Improve performance of RedisInterface#make_list_length by using LTRIM command

---

spec/split_spec.rb
split.gemspec

Fixes #511 
The implementation of #client changed on the redis-rb library on ~> 4.0.1. Which was moved the `#_client`. But as these specs were only checking host/port configs seemed better to call `#connection` instead.
`#connection` returns a Hash from the client settings.

Upgrade fakeredis to 0.7.0

---

lib/split/persistence/cookie_adapter.rb
spec/persistence/cookie_adapter_spec.rb

References #508 and fix a bug introduced by #490
Using ActionDispatch::Cookies from rails, manages flushing/replacing cookies on its own. Sinatra also have something like it on Sinatra::Cookies.
When using Rack directly you have to take care of that. Each time set_cookie was called it was adding another Set-Cookie entry to response.
This PR does:
- Adds back compatibility to ActionDispatch::Cookies. Tries to use it when available
- Fallbacks to parsing/replacing the Set-Cookie header on any Rack app - I still want to think of a more generic/best way to do this.

Fix cookie header duplication

---

.travis.yml
Appraisals
gemfiles/5.1.gemfile
gemfiles/5.2.gemfile

This adds rails 5.2 to appraisals for testing.  I also removed the dependency on git version of sinatra for newer rubies as that does not seem to be necessary at this point.

test rails 5.2 on travis

---

.travis.yml

This adds 2.5.1 to the travis config and updates to the latest 2.4

update ruby versions for travis

---

lib/split/persistence/cookie_adapter.rb
spec/persistence/cookie_adapter_spec.rb

Using `ab_test` from a controller was failing because "cookies" is a private method of the controller instance which is assigned to `@context`.
It looks like this was broken in the commit that fixed the multiple "Set-Cookie" headers bug: https://github.com/splitrb/split/commit/3523e1c53988d727afb3f28a0208d7984f8fc31b
Using `.send(:cookies)` again when using Rails was the easiest way I found to fix this.
Note: I was able to add an integration test for the case when it's called from the controller, but I failed to write a regression test that uses an ActionView context object since that one is more complex to initialize.

CookieAdapter: Fix cookies when @context is an ActionController

---

README.md
lib/split/helper.rb
spec/helper_spec.rb

Facebook, Google etc. have started to do prefetching of landing pages used in campaigns in their mobile apps - without any user interactions.
This PR adds a method to detect these requests and ignore them, as they're non-interactive by the user.
See: https://support.google.com/dcm/partner/answer/7295804?hl=en and https://www.facebook.com/business/help/www/1514372351922333

Ignore previewing requests

---

lib/split/configuration.rb

This PR adds "Facebot" to list of bots.
See: https://developers.facebook.com/docs/sharing/webmasters/crawler/#facebot-crawler

Add Facebot crawler to list of bots

---

lib/split/helper.rb

This PR fixes the context in which the `ignore_filter` is called. This is needed when using the helper methods in a context of an eg. Rails helper.
To illustrate the difference:
```ruby
Split.configure do |config|
config.ignore_filter = ->(request) { puts "{request.class.to_s}" }
end
```
When calling `ab_test` in a controller, the output is:
<ActionDispatch::Request ...>
But when using `ab_test` in a helper, the output is:
<Class...>
This is especially funky due to Rails' delegation of eg. `#headers`, meaning that calling `request.headers` in the `ignore_filter` would have two different meanings - in helpers, it would call `headers` on the **response**, while in controllers it would call `headers` on the **request** (as intended)
This PR fixes the issue and should preserve …

Fix binding of ignore_filter

---

README.md

Recently I started using split gem on a project and tried to find RSpec information in README and it wasn't easy to find for the first time.
I have improved docs reading RSpec part: made it more clear with examples to use, and removed useless assignment at `split_helper.rb`

Improve README regarding RSpec usage

---

lib/split/trial.rb
spec/trial_spec.rb

The `Trial#choose!` method always persist the alternative for an experiment regardless if it has a winner or no. The only difference for them is that they don't `increment_participation` when the experiment has a winner.
The reason why we sometimes see closed experiments and sometimes we don't in the cookies is because when `allow_multiple_experiments` was introduced as a new feature in Split that required to `cleanup_old_experiments` before a new enrolment https://github.com/splitrb/split/commit/a1bc236a0dbb725956120578a339aec26bfb272c. This happens at the beginning of the enrolment, that means that if the last experiment enrolled was closed it will be persisted in the cookie, but if not it will be cleaned for any further enrolment on another experiment.

Do not storage alternative in cookie if experiment has a winner

---

lib/split/dashboard/pagination_helpers.rb

Resolves issue when displaying the dashboard caused by missing
parenthesis is in code for the pagination helper.
After this change the dashboard displays as expected.

Fix Dashboard Pagination Helper typo

---

lib/split/dashboard/helpers.rb

* replace BigDecimal.new() with BigDecimal()
* 3.3.1 and HEAD are affected, most likely affects historical versions as well
* this resolves the following deprecation warning when running Ruby >= 2.5.0rc1:
```
/Users/username/src/project/.gems/gems/split-3.3.1/lib/split/dashboard/helpers.rb:24: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
```

Fix Bigdecimal warnings

---

lib/split.rb

Addresses isssue #528 
Checks to see if Rails::Railtie is defined, and if so sets the Railtie to run before_initialize.  I've run this locally with no issues and specs are passing.

Check to see if being run in Rails application and run in before_initialize

---

lib/split/helper.rb
spec/helper_spec.rb

Closes #482
When Split is disabled or user is excluded, we avoid hitting redis up to load/save the experiment.
This should save a few calls if the a/b is exposed on a public page, or something.
The helper still follows up the logic of building an Split::Experiment to correctly return the control alternative.
Note that on this moment `ExperimentCatalog.find_or_initialize` does actually hit redis to 'find' an existing experiment.

Avoid hitting up on redis for robots/excluded users.

---

lib/split/dashboard.rb
spec/dashboard_spec.rb

Fix https://github.com/splitrb/split/issues/563 by just incrementing participant count when `force_alternative` pushed.
Please review this PR.

Increment participant count when `force_alternative` pushed

---

lib/split/dashboard.rb
spec/dashboard_spec.rb

I closed https://github.com/splitrb/split/pull/565, and resend this patch.
In dashboard, `force_alternative` doesn't work for experiments with incremented version to look for key without version.
This PR fixes this issue and `force_alternative` works for experiments with incremented version.
Please review this.

Fix `force_aleternative` for experiments with incremented version

---

lib/split/experiment.rb
spec/experiment_spec.rb
spec/helper_spec.rb

Fix https://github.com/splitrb/split/issues/521 and TODO in `spec/helper_spec.rb` by adding alternative's weight with name to redis for weight persistence.
Please review this PR.

Persist alternative weights

---

lib/split/helper.rb
spec/helper_spec.rb

Handle correctly case when ab_finished is called before ab_test for a user

---

lib/split/experiment.rb
lib/split/user.rb
spec/dashboard_spec.rb
spec/experiment_spec.rb
spec/user_spec.rb

Reduce the number of redundant Redis operations executed for the same request. This way the performance of a test with combined experiments is expected to improve.
- Cache `Experiment#has_winner?` result for the lifetime of an experiment instance 
- Remove redundant calls to Redis in `Experiment#save`
- Cleanup Split user old experiments only once during the lifetime of a User instance
- Specs added
--
Resolves issue [#573](https://github.com/splitrb/split/issues/573)

Combined experiment performance improvements

---

.rspec
spec/dashboard_spec.rb

Calling calc_winning_alternatives takes too long with a high value on beta_probability_simulations.
That way we were able to gain ~10s locally. Probably more time on travis.

Improve dashboard specs speed.

---

spec/dashboard_helpers_spec.rb

Replace `BigDecimal.new()` with `BigDecimal()` to suppress warnings in specs.
https://github.com/splitrb/split/pull/551 fixed this warning in codes, but didn't in specs. So, this PR fixes this warning in specs.
Following is a warning message.
```
warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
```

Suppress `warning: BigDecimal.new is deprecated;` in specs

---

lib/split/user.rb
spec/helper_spec.rb

Fixes #580 
All calls for experiments keys on User should be gated with `keys_without_finished`. This method filters out all 'finished' keys.
The issue happened because `active_experiments` was loading all `user.keys`. And when calling `key_without_version` method with a 'finished' key with more than 9 versions. Example:
```
irb(main):012:0> key_without_version('exp:11:finished')
=> "exp"
irb(main):013:0> key_without_version('exp:1:finished')
=> "exp:1:finished"
```
It would end up overriding the value of an experiment with the 'exp:11:finished' value from the Storage, which is always 'true'.

When loading active_experiments, it should not look into user's 'finished' keys

---

.travis.yml

Bump ruby versions for travis because ruby 2.6.4/2.5.6/2.4.7 have been released.
Reference:
- https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-6-4-released/
- https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-5-6-released/
- https://www.ruby-lang.org/en/news/2019/08/28/ruby-2-4-7-released/

Bump ruby versions because ruby 2.6.4/2.5.6/2.4.7 have been released

---

README.md

This issue is related to https://github.com/splitrb/split/issues/185.
I ran into the same problem when creating an experiment that used symbols in the experiment's metadata configuration. This caused `Split::Experiment#experiment_configuration_has_changed?` to always return `true`, which reset the experiment. 😭 
```ruby
Split.configure do |config|
config.experiments = {
my_first_experiment: {
alternatives: ["a", "b"],
metadata: {
"a" => { text: "Hello" },
"b" => { text: "Hi" }
}
}    
}
end
```
Maybe `split` should stringify metadata hash keys? I'm not convinced it should, but I do think this behavior should be noted in the README.

Update README.md to mention metadata key issue

---

lib/split/persistence/dual_adapter.rb
spec/persistence/dual_adapter_spec.rb

1. Given a user that hasn't been bucketed before in a running experiment.
2. When accessing a logged out page he/she is bucketed with version `A`.
3. When logging in
Expected Result:
Version `A` is still being shown. 
Actual Result:
The current `DualAdapter` will just leave it up to the `logged_in_adapter` which has no information of that user, and any version could be chosen.
Related issue https://github.com/splitrb/split/issues/483
Currently, the `DualAdapter` make use of the `logged_in_adapter` and `logged_out_adapter` in a  complete independent way. Because of that, the user won't have a consistent experience across logged in and logged out pages. This could also affect the conversions depending on how the experiment is set up. For example if the goal is in a logged in page, if …

Improve DualAdapter

---

lib/split/alternative.rb
lib/split/configuration.rb
lib/split/experiment.rb
lib/split/trial.rb
spec/encapsulated_helper_spec.rb
spec/experiment_spec.rb
spec/helper_spec.rb

Avoid redefining accessor methods and ambiguous arguments.

Fix ruby warnings

---

lib/split/configuration.rb
lib/split/dashboard/pagination_helpers.rb
spec/dashboard/pagination_helpers_spec.rb

Some people (like me) may prefer slower initial dashboard pageloads then
searching within the page vs. having to load many pages to try and find
the A/B test of interest to them.
Making the default "tests per page" parameter configurable gives that flexibility.
Test Plan:
rspec

Make dashboard pagination default "per" param configurable

---

lib/split/engine.rb

Reference ActionController directly when including split helpers

---

lib/split/experiment.rb
spec/experiment_spec.rb

Addresses issue https://github.com/splitrb/split/issues/598

Respect experiment defaults when loading experiments in initializer.

---

README.md
lib/split/configuration.rb
lib/split/experiment.rb
spec/experiment_spec.rb

Related to https://github.com/splitrb/split/issues/571

Add on_winner_choose hook

---

lib/split/user.rb
spec/helper_spec.rb

When using allow_multiple_experiments=control Split only allows one
experiment with an alternative other than 'control'.
Split::User#max_experiments_reached? checks for that looping through all
experiments. As Split::User#active_experiments drop the experiment
version we also need to do that here to be able to check properly.
Fixes #612

Fix #max_experiments_reached? when using allow_multiple_experiments=control

---

lib/split/algorithms/whiplash.rb
lib/split/experiment.rb
split.gemspec

This replaces the usage of the Beta Distribution RNG parts.
No behavior was changed by this.

Replace usage of SimpleRandom with RubyStats

---

lib/split/experiment.rb

Removes code that is not called(?) and has already been addressed in `extract_alternatives_from_options()`. More specifically the function checks whether or not the alternatives were passed via the options as params, which will then already proceeds to try loading them from Split.configuration.experiments ~> no reason for the outer `initialize()` to try to do the same.
- Makes it easier to read
- Removes code from initialize

Removed repeated loading from config

---

lib/split/helper.rb
spec/encapsulated_helper_spec.rb
spec/helper_spec.rb

Split returns 'control' when disabled/excluded users/redis connection issues.
Before: Split yield {} as metadata even if there was one available.
After: If there's a metadata associated with the alternative, split will yield the metadata.
This will also make the behavior consistent between all scenarios. Unless the metadata is not defined on the configuration files.
ExperimentCatalog.find_or_initialize does not make any redis calls, so it's safe to use 'experiment' because it loads data from configuration.
Fixes #618

ab_test must return metadata on error or if split is disabled/excluded user

---

lib/split/dashboard.rb
lib/split/dashboard/public/dashboard.js
lib/split/dashboard/public/style.css
lib/split/dashboard/views/_controls.erb
lib/split/experiment.rb
lib/split/trial.rb
spec/dashboard_spec.rb
spec/experiment_spec.rb
spec/trial_spec.rb

Disabling Cohorting: Allow existing registered participants time to convert while no longer accepting new participants into the experiment. New participants will be given the control will be given the control and will not be recorded as being apart of the experiment.
- Gives implementers the ability to soft close experiments, allowing shifting new participants into other experiments before concluding the result of the experiment (selecting a winner).
- Allows for better accuracy of data, ~> allows participants the chance to convert if they engaged late before the end of the experiment.
- Adds enable/disable button to the dashboard
- Provides a brief alert description describing the resulting behaviour when performed.
- Adds functions to the experiment object to check and mutate the flag …

Introduce enable/disable experiment cohorting

---

lib/split/helper.rb
lib/split/trial.rb
spec/helper_spec.rb
spec/trial_spec.rb

When using goals the `on_trial_complete` does not have scope to the `#ab_finished` supplied goals.
Updates the Trial to initialize with goals so that they are accessible in the callback when passing the trial into the callback.
Notes: Fixed and cleaned up specs.

Update Trial so that goals are accessible in callback

---

.travis.yml
split.gemspec

Support of Ruby 2.4 has ended this year.

Only support Ruby versions >= 2.5

---

.travis.yml
lib/split/experiment.rb
lib/split/experiment_catalog.rb
spec/alternative_spec.rb
spec/configuration_spec.rb
spec/experiment_spec.rb
spec/goals_collection_spec.rb
spec/spec_helper.rb
split.gemspec

redis-rb 2.2 was released long ago, it's time to update the minimum required deps.
Also drops fakeredis, so we can test using real Redis instances on CI.

Bump minimum required redis to 4.2

---

lib/split/redis_interface.rb
spec/redis_interface_spec.rb

When persisting a list several calls are being made to ensure that each element gets the correct index.
Instead of dealing with that on a single [MULTI](https://redis.io/topics/transactions) call, we push all elements to a tmp list, and that gets renamed it right after, using [RENAME](https://redis.io/commands/rename) overwriting the previous list.
Also, this is only called on new experiments, and whenever an experiment configuration has changed.
Before:
- N RPUSH calls would be made.
- N LSET calls would be made, depending on the scenario.
- 1 extra LTRIM 
Now:
- Single RPUSH with all the alternatives O(n) where n is the number of elements
- 1 RENAME O(1). 
Also removing one extra SISMEMBER check when calling RedisInterface#add_to_set.

Simplify RedisInterface usage when persisting Experiment alternatives

---

README.md

As far as I understand, under GDPR law someone would still need to ask consent for storing cookies, even though split does not store any "personal identifiable info" other than experiment names and variants.
Closes #523

Adding documentation related to what is stored on cookies.

---

lib/split/dashboard.rb
lib/split/helper.rb
spec/dashboard_spec.rb

When using the admin dashboard and forcing an experment, this should not count
on metrics and should be only used for testing.

Force experiment does not count for metrics

---

lib/split/dashboard.rb
lib/split/dashboard/action.rb
lib/split/dashboard/helpers.rb
lib/split/dashboard/pagination_helpers.rb
lib/split/dashboard/rendering.rb
lib/split/dashboard/routing.rb
lib/split/dashboard/views/_experiment.erb
lib/split/dashboard/views/_experiment_with_goal_header.erb
lib/split/dashboard/views/index.erb
lib/split/dashboard/web.rb
spec/dashboard/pagination_helpers_spec.rb
spec/dashboard_helpers_spec.rb
spec/dashboard_spec.rb
split.gemspec

Rework on top of #561 it works now 🚀 
Sinatra is only being used for the dashboard. With this PR, we remove this dependency entirely. As we're adding sinatra for several rails apps that are not using sinatra, this is a good thing 🙌

Remove Sinatra Dependency for Split Dashboard

---

lib/split/experiment.rb

One less network roundtrip to Redis during ab_test.

Single HSET to update values, instead of multiple ones. 

---

lib/split/persistence.rb
lib/split/persistence/redis_adapter.rb
lib/split/user.rb
spec/persistence/redis_adapter_spec.rb
spec/user_spec.rb

On situations where one might need to recover the ab_test a user is on, this will be helpful. It's possible to do this with the current API, but It requires passing a few 'nil' contexts around. 
```
Split::User.find(11, :redis).active_experiments
=> {"link_text_2"=>"Click Here"}
```
Not fully decided on the API, so this can change. Also, note that this won't work with cookie_adapters etc. 
Closes #489

add a simple way to load users outside web session

---

lib/split/trial.rb

There is a class variable, `alternative_choosen` in the `Split::Trial`
class. This class variable has a typo. The correct spelling should be
[`alternative_chosen`](http://www.english-for-students.com/Chosen-vs-Choosen.html)
This commit fixes the class variable typo and updates all usage of the
class variable. The class variable is only used within the class itself.

Fix typo of in `Split::Trial` class variable

---

README.md
lib/split/cache.rb
lib/split/experiment.rb
lib/split/experiment_catalog.rb
spec/cache_spec.rb

1. Adds caching in the experiment save path to use the cached experiment config instead of making redis calls to compare new and existing configs.
2. Have cache clear in the `Experiment#reset` call which allows runtime update of experiment config without reboot required.
3. Have cache clear in the `Experiment#reset_winner` call which allows runtime update of experiment winner without reboot required.

Caching based optimization in the experiment#save path

---

lib/split/experiment.rb

HMSET is deprecated in favor of HSET on Redis  4.0 (not redis-rb). https://redis.io/commands/hmset But, we still need to keep compatibility for now.

Uset Redis#hmset to keep compatibility with Redis < 4.0

---

lib/split/user.rb
spec/user_spec.rb

I've found that `Split::User#cleanup_old_versions!` method misbehaves when you have multiple running experiments with some common strings in their names.
For example if you have running both `some_test` and `some_test_variation` (or even `variation_of_some_test`), then calling `cleanup_old_versions!` for the first experiment will also drop data for the latter one.
The outcome of this behaviour looks very confusing.
In my case I see participant numbers increase on each page refresh for the second and further tests running in the user session, despite the counter must be unique
Don't use regular expression to match experiment names. 
Experiment version keys should be compared from their start and until the colon symbol (`some_test:42` is the example of what is actually stored within …

Fix cleanup_old_versions! misbehaviour

---

lib/split/configuration.rb
lib/split/persistence/cookie_adapter.rb
spec/configuration_spec.rb

Allows option to set the domain property of the cookie, so that the library can work across different subdomains.

Adds config option for cookie domain

---

lib/split.rb

This `::Railtie` top-level constant looked lost. I think it belongs to you?

Keep railtie defined under the Split gem namespace

---

README.md

Adds support for the helpers block form  `ab_test(:experiment) { |variant| ... }`, based on the example from RSpec's docs[1].
[1]: https://relishapp.com/rspec/rspec-mocks/v/3-2/docs/configuring-responses/block-implementation#yield-to-the-caller's-block

Update RSpec helper to support block syntax

---

Gemfile
lib/split.rb
lib/split/algorithms.rb
lib/split/algorithms/whiplash.rb
lib/split/experiment.rb

- Encapsulates RubyStats on its own module. Avoiding calling it from other places in code. Split just needs the BetaDistribution.
- Warns if matrix is not installed ([stblib made it into a gem](https://github.com/ruby/matrix)). Although this should be fixed on rubystats upstream, for now, we try to warn users and to make our own specs pass.

Encapsulate Split::Algorithms at our own module to avoid explicit calling rubystats everywhere

---

spec/combined_experiments_helper_spec.rb
spec/encapsulated_helper_spec.rb
spec/experiment_spec.rb
spec/helper_spec.rb
spec/spec_helper.rb

For example:
```
The implicit block expectation syntax is deprecated, you should pass a block rather than an argument to `expect` to use the provided block expectation matcher or the matcher must implement `supports_value_expectations?`. e.g  `expect { value }.to raise Exception` not `expect(value).to raise Exception`
```
Also configured rspec to raise deprecations as errors.

Remove usage of deprecated implicit block expectation from specs

---

lib/split/dashboard.rb
lib/split/dashboard/public/style.css
lib/split/dashboard/views/index.erb
spec/dashboard_spec.rb

When using the start_manually experiment configuration, an experiment cannot be started unless ab_test is called so that the experiment is initialized ~ added to the dashboard.
- Adds an endpoint to the dashboard to initialize a given experiment.
- Adds a dropdown to the dashboard populated with all the preconfigured experiments that have yet to be initialized.

Add ability to initialize experiments

---

lib/split/dashboard.rb

...and not an application
```
NoMethodError: undefined method `env' for Rails:Module
/bundle/ruby/3.0.0/gems/split-3.4.1/lib/split/dashboard.rb:28:in `block in <class:Dashboard>'
```

Handle when Rails is partially loaded as a Gem

---

lib/split/alternative.rb
lib/split/experiment.rb
spec/experiment_spec.rb

**Problem**
CI fails on `main`. 
Turns out that Redis [started using `redis-client` gem as a transport layer](https://github.com/redis/redis-rb/commit/08a21001b5f27088a412fbe7a6fba8d558eade40#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55fR12), which raises errors on non-string types.
> <img width="883" alt="image" src="https://user-images.githubusercontent.com/2563994/189643408-d49fcc44-5498-49e0-9e05-9525fb6f16de.png">
**Solution**
Cast redis arguments to strings until tests pass :-)
**Notes**
That should unblock working on actual features/fixes

Add support for redis-client, which does not automatically cast types to strings

---

lib/split/persistence/cookie_adapter.rb
spec/persistence/cookie_adapter_spec.rb

**Problem**
When `split` cookie is a valid, json encoded String, a `NoMethodError` is raised. (See https://github.com/splitrb/split/issues/695 )
**Solution**
Add an empty hash fallback for unsupported types
Resolves #695 
**Notes**
- The pre-existing test for invalid JSON seemed broken, so I (hopefully) fixed it

Stop crashing on non-hash json

---

lib/split/redis_interface.rb
spec/redis_interface_spec.rb

Fixes the following deprecation warning when using Redis 4.8.0:
```
Redis#sadd will always return an Integer in Redis 5.0.0.
Use Redis#sadd? instead.
```
As the return value of `redis.sadd` is not used, we can simply replace the `.sadd` call with `.sadd?`.
see
- https://github.com/redis/redis-rb/blob/4.x/CHANGELOG.md#480
- #700

Fix deprecation warning with Redis 4.8.0

---

lib/split/experiment.rb
spec/dashboard_spec.rb
spec/experiment_spec.rb
spec/spec_helper.rb

We stumbled on situation at work where we had a completed_count greater than participant_count. 
When calculating the probability this can lead to negative numbers which are not valid input for Beta Distribution. So  RubyStats throws an error right away. 
I still need more info on when/how this happens. But the Dashboard should not blow up in any case because of this. So I'm adding this check.

Do not throw error if alternativas have data that can lead to negative numbers for probability calculation

---

Gemfile
gemfiles/7.0.gemfile
lib/split/algorithms.rb
split.gemspec

Matrix is actually a dependency from rubystats, which we use for beta_distribution.
For now, I think it's ok to ensure matrix is loaded as a split dependency as we always require it. 
Closes #704

Add matrix as a default dependency

---

lib/split/redis_interface.rb

Addresses issue https://github.com/splitrb/split/issues/709
- Intentionally did not write test as we will need to set up Redis cluster in `spec/spec_helper.rb` based on the compatible redis gem version.

CROSSSLOT keys issue fix when using redis cluster

---

README.md

The example about accessing the user outside of a web session is currently broken. It's possible to access the storage for the user by the following: 
```ruby
user = Split::User.find(user_id, :redis) 
user.active_experiments
```

Update documentation regarding finding users outside a web session

---

lib/split/dashboard/views/_experiment.erb
lib/split/helper.rb
spec/helper_spec.rb

If an invalid value is persisted on a given alternative, that dashboard is able to validate the data properly now.
Added a few specs to ensure extra_info is persisted correctly.
This is an alternative for #707

Do not persist invalid extra_info on ab_record_extra_info.

---

spec/persistence/cookie_adapter_spec.rb

The response from context.response.headers["Set-Cookie"]) changed a bit, so I'm updating the specs to reflect that between older/newer versions of rack.
There's also a new deprecation that needs to be addressed. Will do it on a later PR. 
```
warning: Rack::Response#header is deprecated and will be removed in Rack 3.1
```

Make specs compatible with newer rack

---

lib/split/encapsulated_helper.rb
lib/split/helper.rb
spec/encapsulated_helper_spec.rb
spec/spec_helper.rb

I'll try to summarize the problem as much as possible:
The split has this class:
```ruby
class ContextShim
include Split::Helper
public :ab_test, :ab_finished
def initialize(context)
@context = context
end
def ab_user
@ab_user ||= Split::User.new(@context)
end
end
```
Which includes:
```ruby
include Split::Helper
```
If we use the context shim this way:
```ruby
def split
@split ||= ::Split::EncapsulatedHelper::ContextShim.new(self) 
end
```
inside a high level abstraction, we got a problem.
The override of ab via URL (`?ab_test[my_test]=variant`) and Split panel (cookies) doesn't work.
It doesn't work because `Split::Helper` uses these methods:
```ruby
def override_alternative_by_params(experiment_name)
defined?(params) && params[OVERRIDE_PARAM_NAME] && …
```

Fix context shim override behavior

---

split.gemspec

Added the funding_uri to the gemspec to help increase visibility using the `bundle fund` command in Bundler.

Add funding_uri to gemspec
