splitrb/split

lib/split/trial.rb, spec/trial_spec.rb
Also support passing Goals and a single goal
=> Revert the Trial#complete! public API to support noargs.

README.md, lib/split.rb
Configure Redis using environment variables like Heroku or other [12factor](http://12factor.net/config) applications.
*P.S. Sorry for whitespaces at end of lines, truncated with vim automatically :)*
=> Redis configuration using environment variables

lib/split/helper.rb, lib/split/trial.rb, spec/helper_spec.rb
now i can use metadata in views:
```slim
/ slim sample:
- ab_test('my_experiment') do |alternative, meta|
h2 
= alternative
small = meta['subtitle']
```
=> Push metadata to ab_test block

README.md
Sorry, i forgot about readme in previous PR #296
=> Update README section about metadata

.travis.yml, spec/configuration_spec.rb, spec/experiment_catalog_spec.rb, spec/experiment_spec.rb, spec/helper_spec.rb, spec/persistence/redis_adapter_spec.rb, spec/persistence_spec.rb, split.gemspec
Mostly for rspec 3.4, fixed a load of spec warnings too
=> Update development dependencies

lib/split/dashboard/views/_controls.erb
Sorry, when I fixed the dashboard to allow names with slashes I forgot up update the delete button url.
=> Whoops. Forgot to update the delete path.

README.md
=> Clarify finished with first option being a hash

README.md
=> README: clarify multiple goals

lib/split/configuration.rb
- Convert `if condition nil...else` clause to `return nil if condition`
- Store experiment_data in a hash and iterate over all values and
assign them to experiment_config only when set
**Assumptions**: I assume that `settings[key]` where key in `(:goals,
:alternatives, :metadata, :algorithm)` will never return `false`.
For the key `:resettable`, it will return `false` if set to `false`.
=> Simplify Configuration#normalized_experiments

.travis.yml, Gemfile, spec/spec_helper.rb, split.gemspec
Removing the need for redis on travis or other test environments with https://github.com/guilleiguaran/fakeredis
=> Use fakeredis for testing

CHANGELOG.md, README.md, lib/split/persistence.rb, lib/split/persistence/dual_adapter.rb, lib/split/version.rb
Issue #404 Use different persistence adapter for logged-in vs. logged-out users
Note: this branch first merges v1.5.0 into master branch which had diverged.
=> 144867444998371 dual cookie redis split persistence adapter

CHANGELOG.md
=> CHANGELOG: Mention that 2.2.0 is backwards incompatible

lib/split.rb, lib/split/persistence.rb, lib/split/persistence/dual_adapter.rb, lib/split/user.rb
The travis build now seems to work again.
=> Fix loadorder issues

CONTRIBUTING.md, LICENSE, README.md
I've updated your README, heavily extended the Contribute, and updated the year in the license file. See email for more. Thank you! 
Feel free to comment here, or request changes.
=> Repository Audit by Maintainer.io

.travis.yml, lib/split/helper.rb, split.gemspec
See #494.
https://github.com/splitrb/split/blob/07b71cec9f220a16795811dcf9feca5d795bd15f/split.gemspec#L24
=> CI: Change and test earliest supported Ruby version (1.9.2 -> 2.2.0)

README.md
=> Document the option `reset_manually`

lib/split/trial.rb, spec/trial_spec.rb
=> Fix user participating alternative not found

.travis.yml, split.gemspec
Also bump ruby versions for a few rubies
=> Update travis config and add Ruby 2.6.0

lib/split/configuration.rb
[UptimeRobot](https://uptimerobot.com/) is an uptime monitoring service not yet excluded by split.
=> Added uptime robot to configuration.rb

split.gemspec
In this pull request I fix the specs that break in the development environment by not having gem of the rails
=> Fix broken specs in developement environment

lib/split/configuration.rb
fixes https://github.com/splitrb/split/issues/605 
as per https://help.pinterest.com/en/business/article/pinterest-crawler
=> Only block Pinterest bot

lib/split/experiment.rb, spec/experiment_spec.rb
=> Removes metadata key when it updated to nil

CONTRIBUTING.md, split.gemspec
=> Fix default branch name and gem metadata indentation

lib/split.rb
Handle when Rails is partially loaded as a Gem. Check for specific class.
=> check specfic class - VYD-15128
